### PR TITLE
Fix URL fetch for BCO Published Objects

### LINKED ISSUE #37: Object ID Versioning
The BCO_API should handle versioning the way NCBI does for GenBank records.  
For Example: 
- https://biocomputeobject.org/BCO_28/1.1 
- https://biocomputeobject.org/BCO_28/1.0 

should be different object in the DB but available by requesting that specific URL or object...

but https://biocomputeobject.org/BCO_28 should ONLY return https://biocomputeobject.org/BCO_28/1.1 as that is the most RECENT version. 

Also the object listing [`/api/objects/token/`] should only return the most RECENT version by default.

### PR DESCRIPTION
**Pull request by syntheticgio**
Supports the call:

`/<PREFIX>_<BCO_NAME>/<BCO VERSION>`

Closes #37

### CODE REVIEW

**Comment by syntheticgio** [comment]
Working example:  `http://localhost:8000/BCO_000010/1.0` So the format <URL>/<BCO_NAME>/<VERSION> works (does not specifically worry about the prefix, although may want to worry about that later depending on how we store these).

**Comment by syntheticgio** [comment]
I think this is ready to test @HadleyKing - looks to be working for me (if version is requested, going to follow up w/o version to get the most recent).  I had played around with splitting the prefix from the bco name - but it seems like the bco name includes the prefix and so doesn't need to have it split out?

**Comment by syntheticgio** [comment]
Looks like we will need to do something more like `http://localhost:8000/bcos/BCO_000010/1.0` @HadleyKing - it appears having a regex for the first item in the URL doesn't work unless there are thigns following it.  Not sure if it is just django limitation or if there is something special you need to do; but prefixing the BCO ID fixes the issue.  I'd propose:

`http://localhost:8000/bcos/BCO_000010`
`http://localhost:8000/bcos/BCO_000010/1.0`

As examples which get you the basic functionality.  The 'bcos' part could also be 'api' if we want to match the current way we're constructing these (although it doesn't matter).  What do you think?

**Comment by syntheticgio** [comment]
Ready for review @HadleyKing

**Review by HadleyKing — APPROVED** [review]

**Pull request merged**
